"""patiend data creation with symptom

Revision ID: 582844a86c25
Revises: 
Create Date: 2023-06-17 13:51:19.243706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582844a86c25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symptom',
    sa.Column('symptom_code', sa.String(length=100), nullable=False),
    sa.Column('symptom_name', sa.String(length=100), nullable=True),
    sa.Column('symptom_diagnostic', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('symptom_code')
    )
    op.create_table('business',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=100), nullable=True),
    sa.Column('symptom_code', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['symptom_code'], ['symptom.symptom_code'], ),
    sa.PrimaryKeyConstraint('business_id', 'symptom_code')
    )
    # ### end Alembic commands ###
    


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business')
    op.drop_table('symptom')
    # ### end Alembic commands ###
