"""database is generated

Revision ID: 8dd9896351b9
Revises: 4a0d617916d8
Create Date: 2023-06-17 20:48:23.835535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd9896351b9'
down_revision = '4a0d617916d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
