"""database is generated

Revision ID: 4a0d617916d8
Revises: 582844a86c25
Create Date: 2023-06-17 16:04:20.424465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a0d617916d8'
down_revision = '582844a86c25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
